server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    #配置连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接数
      initial-size: 3
      #最大连接数
      max-active: 20
      #最大等待时间，单位：ms
      max-wait: 60000
      #最小空闲数
      min-idle: 3
mybatis-plus:
  #配置mapper.xml文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #关闭缓存
    cache-enabled: false
    #数据表中如果有下划线，自动映射到驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      damaomao: debug